name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'  # укажи нужную стабильную версию
          channel: stable
          cache: true

      # 3. Делаем скрипт исполняемым
      - name: Make ci_setup.sh executable
        run: chmod +x ./ci_setup.sh

      # 4. Запускаем скрипт CI
      - name: Run CI setup script
        run: ./ci_setup.sh

      # 5. Загружаем собранный APK как артефакт (если есть)
      - name: Upload APK artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
