name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Create Flutter project
        run: |
          flutter create app
          cp -r lib app/ || true
          cp pubspec.yaml app/ || true

      - name: Patch Kotlin version
        run: |
          # В build.gradle обновляем ext.kotlin_version на 1.9.24
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.24"/' app/android/build.gradle || true
          # В settings.gradle тоже обновляем, если есть блок plugins
          sed -i 's/id "org.jetbrains.kotlin.android" version ".*"/id "org.jetbrains.kotlin.android" version "1.9.24"/' app/android/settings.gradle || true

      - name: Get dependencies
        working-directory: app
        run: flutter pub get

      - name: Build APK
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
