name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Create Flutter project
        run: |
          flutter create app
          cp -r lib app/
          cp pubspec.yaml app/ || true

      - name: Update Kotlin and Gradle
        run: |
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.24"/' app/android/build.gradle
          sed -i 's/com.android.tools.build:gradle:[0-9.]\+/com.android.tools.build:gradle:8.3.2/' app/android/build.gradle
          sed -i 's/distributionUrl=.*gradle-[0-9.]\+-all.zip/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.7-all.zip/' app/android/gradle/wrapper/gradle-wrapper.properties

      - name: Build APK
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
