name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.10.6'
          cache: true

      - name: (Optional) Checkout specific version if needed
        run: |
          cd $FLUTTER_ROOT
          git fetch --tags
          git checkout 3.10.7
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure Android permissions in manifest
        run: |
          MANIFEST_FILE=android/app/src/main/AndroidManifest.xml
          if ! grep -q "RECORD_AUDIO" "$MANIFEST_FILE"; then
            sed -i '0,/<application>/s//<uses-permission android:name=\"android.permission.RECORD_AUDIO\" \/>\\n<uses-permission android:name=\"android.permission.WRITE_EXTERNAL_STORAGE\" \/>\\n<uses-permission android:name=\"android.permission.READ_EXTERNAL_STORAGE\" \/>\\n\\n<application>/' $MANIFEST_FILE
          fi

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build APK
        if: github.event_name == 'push'
        run: flutter build apk --release

      - name: Upload APK artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
