name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.9' # можно заменить на нужную стабильную версию
          cache: true

      - name: Ensure Flutter project structure
        run: |
          if [ ! -d "android" ] || [ ! -d "ios" ]; then
            echo "Создаём недостающие платформенные директории..."
            flutter create .
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure Android permissions in manifest
        run: |
          MANIFEST_FILE=android/app/src/main/AndroidManifest.xml
          if [ -f "$MANIFEST_FILE" ]; then
            if ! grep -q "RECORD_AUDIO" "$MANIFEST_FILE"; then
              sed -i '0,/<application>/s//<uses-permission android:name="android.permission.RECORD_AUDIO" \/>\
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" \/>\
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" \/>\
\
<application>/' $MANIFEST_FILE
            fi
          fi

      - name: Ensure iOS Info.plist permissions
        run: |
          INFO_PLIST=ios/Runner/Info.plist
          if [ -f "$INFO_PLIST" ]; then
            if ! grep -q "NSMicrophoneUsageDescription" "$INFO_PLIST"; then
              plutil -insert NSMicrophoneUsageDescription -string "Приложению нужен доступ к микрофону чтобы записывать голос" "$INFO_PLIST" || true
            fi
          fi

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build APK (release)
        if: github.event_name == 'push'
        run: flutter build apk --release

      - name: Upload APK artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
