name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Create Flutter project
        run: |
          flutter create app
          cp -r lib app/ || true
          cp pubspec.yaml app/ || true

          # Добавляем INTERNET + STORAGE + NOTIFICATIONS
          sed -i '/<application/i\    <uses-permission android:name="android.permission.INTERNET"/>' app/android/app/src/main/AndroidManifest.xml
          sed -i '/<application/i\    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>' app/android/app/src/main/AndroidManifest.xml
          sed -i '/<application/i\    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' app/android/app/src/main/AndroidManifest.xml
          sed -i '/<application/i\    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>' app/android/app/src/main/AndroidManifest.xml

          # Обновляем compileSdk и targetSdk
          sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 34/' app/android/app/build.gradle || true
          sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 34/' app/android/app/build.gradle || true

          # Проверяем, если Gradle использует namespace, задаем его
          if ! grep -q "namespace" app/android/app/build.gradle; then
            echo 'android { namespace "com.example.app" }' >> app/android/app/build.gradle
          fi

      - name: Get dependencies
        working-directory: app
        run: flutter pub get

      - name: Build APK
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
