name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Create Flutter project
        run: |
          flutter create app
          cp -r lib app/ || true
          cp pubspec.yaml app/ || true

          # Добавляем INTERNET permission
          sed -i '/<application/i\    <uses-permission android:name="android.permission.INTERNET"/>' app/android/app/src/main/AndroidManifest.xml

      - name: Patch Kotlin & Gradle
        run: |
          # Kotlin 1.9.24
          sed -i 's/ext.kotlin_version = .*/ext.kotlin_version = "1.9.24"/' app/android/build.gradle || true
          sed -i 's/id "org.jetbrains.kotlin.android" version ".*"/id "org.jetbrains.kotlin.android" version "1.9.24"/' app/android/settings.gradle || true

          # Android Gradle Plugin 8.3.2
          sed -i 's/com.android.tools.build:gradle:[0-9.]*/com.android.tools.build:gradle:8.3.2/' app/android/build.gradle || true

          # Gradle Wrapper 8.6
          mkdir -p app/android/gradle/wrapper
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.6-all.zip" > app/android/gradle/wrapper/gradle-wrapper.properties

          # compileSdk / targetSdk = 35
          sed -i 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 35/' app/android/app/build.gradle || true
          sed -i 's/targetSdkVersion [0-9][0-9]*/targetSdkVersion 35/' app/android/app/build.gradle || true

      - name: Get dependencies
        working-directory: app
        run: flutter pub get

      - name: Build APK
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
